version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Api.TorMarket.WebApi/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__Default=Server=db;Database=TorMarketDb;User=sa;Password=Your_admin123;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_admin123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: